In [83]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics  import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import ExtraTreeClassifier

In [85]:
#Importando dados de aprovação de credito
credito=pd.read_csv("Credit2.csv", sep=";")
credito

ID checking_status                  credit_history  duration   
0       1              <0  critical/other existing credit         6  \
1       2        0<=X<200                   existing paid        48   
2       3     no checking  critical/other existing credit        12   
3       4              <0                   existing paid        42   
4       5              <0              delayed previously        24   
..    ...             ...                             ...       ...   
995   996     no checking                   existing paid        12   
996   997              <0                   existing paid        30   
997   998     no checking                   existing paid        12   
998   999              <0                   existing paid        45   
999  1000        0<=X<200  critical/other existing credit        45   

     credit_amount  installment_commitment  residence_since  age   
0             1169                       4                4   67  \
1             5951                       2                2   22   
2             2096                       2                3   49   
3             7882                       2                4   45   
4             4870                       3                4   53   
..             ...                     ...              ...  ...   
995           1736                       3                4   31   
996           3857                       4                4   40   
997            804                       4                4   38   
998           1845                       4                4   23   
999           4576                       3                4   27   

     existing_credits  num_dependents class  
0                   2               1  good  
1                   1               1   bad  
2                   1               2  good  
3                   1               2  good  
4                   2               2   bad  
..                ...             ...   ...  
995                 1               1  good  
996                 1               1  good  
997                 1               1  good  
998                 1               1   bad  
999                 1               1  good  

[1000 rows x 11 columns]

In [86]:
#Retirando a coluna id e checking status por que não serve para o modelo
credito = credito.iloc[:,2:]
credito

credit_history  duration  credit_amount   
0    critical/other existing credit         6           1169  \
1                     existing paid        48           5951   
2    critical/other existing credit        12           2096   
3                     existing paid        42           7882   
4                delayed previously        24           4870   
..                              ...       ...            ...   
995                   existing paid        12           1736   
996                   existing paid        30           3857   
997                   existing paid        12            804   
998                   existing paid        45           1845   
999  critical/other existing credit        45           4576   

     installment_commitment  residence_since  age  existing_credits   
0                         4                4   67                 2  \
1                         2                2   22                 1   
2                         2                3   49                 1   
3                         2                4   45                 1   
4                         3                4   53                 2   
..                      ...              ...  ...               ...   
995                       3                4   31                 1   
996                       4                4   40                 1   
997                       4                4   38                 1   
998                       4                4   23                 1   
999                       3                4   27                 1   

     num_dependents class  
0                 1  good  
1                 1   bad  
2                 2  good  
3                 2  good  
4                 2   bad  
..              ...   ...  
995               1  good  
996               1  good  
997               1  good  
998               1   bad  
999               1  good  

[1000 rows x 9 columns]

In [87]:
#Renomeando as coluna em ingles para Portuguese 
credito=credito.rename(columns={'credit_history':'histórico de crédito',"duration":"duração", "credit_amount":"quantidade de crédito", "installment_commitment" : 'compromisso de parcelamento', "residence_since": "residência desde",
                                "age":"idade", "existing_credits":"créditos existentes", "num_dependents":"número de dependentes" })
credito


histórico de crédito  duração  quantidade de crédito   
0    critical/other existing credit        6                   1169  \
1                     existing paid       48                   5951   
2    critical/other existing credit       12                   2096   
3                     existing paid       42                   7882   
4                delayed previously       24                   4870   
..                              ...      ...                    ...   
995                   existing paid       12                   1736   
996                   existing paid       30                   3857   
997                   existing paid       12                    804   
998                   existing paid       45                   1845   
999  critical/other existing credit       45                   4576   

     compromisso de parcelamento  residência desde  idade   
0                              4                 4     67  \
1                              2                 2     22   
2                              2                 3     49   
3                              2                 4     45   
4                              3                 4     53   
..                           ...               ...    ...   
995                            3                 4     31   
996                            4                 4     40   
997                            4                 4     38   
998                            4                 4     23   
999                            3                 4     27   

     créditos existentes  número de dependentes class  
0                      2                      1  good  
1                      1                      1   bad  
2                      1                      2  good  
3                      1                      2  good  
4                      2                      2   bad  
..                   ...                    ...   ...  
995                    1                      1  good  
996                    1                      1  good  
997                    1                      1  good  
998                    1                      1   bad  
999                    1                      1  good  

[1000 rows x 9 columns]

In [88]:
#Separando a coluna de instancias e classe
previsores = credito.iloc[:,0:8]
classe = credito.iloc[:, 8]
classe

0      good
1       bad
2      good
3      good
4       bad
       ... 
995    good
996    good
997    good
998     bad
999    good
Name: class, Length: 1000, dtype: object

In [89]:
#Transformando coluna categórica em numérica
encoding=LabelEncoder()
previsores["histórico de crédito"]=encoding.fit_transform(previsores["histórico de crédito"])
previsores

histórico de crédito  duração  quantidade de crédito   
0                       1        6                   1169  \
1                       3       48                   5951   
2                       1       12                   2096   
3                       3       42                   7882   
4                       2       24                   4870   
..                    ...      ...                    ...   
995                     3       12                   1736   
996                     3       30                   3857   
997                     3       12                    804   
998                     3       45                   1845   
999                     1       45                   4576   

     compromisso de parcelamento  residência desde  idade   
0                              4                 4     67  \
1                              2                 2     22   
2                              2                 3     49   
3                              2                 4     45   
4                              3                 4     53   
..                           ...               ...    ...   
995                            3                 4     31   
996                            4                 4     40   
997                            4                 4     38   
998                            4                 4     23   
999                            3                 4     27   

     créditos existentes  número de dependentes  
0                      2                      1  
1                      1                      1  
2                      1                      2  
3                      1                      2  
4                      2                      2  
..                   ...                    ...  
995                    1                      1  
996                    1                      1  
997                    1                      1  
998                    1                      1  
999                    1                      1  

[1000 rows x 8 columns]

In [90]:
#Separando dados de treino e teste
x_treino,x_teste,y_treino,y_teste = train_test_split(previsores, classe, test_size=0.3 , random_state=0)

In [91]:
#Atribuindo algoritmo e estimando número de arvores
floresta = RandomForestClassifier(n_estimators=1000)
floresta.fit(x_treino,y_treino)

RandomForestClassifier(n_estimators=1000)

In [92]:
#fazendo previsões com meu com meu modelo
previsoes = floresta.predict(x_teste)
previsoes

array(['bad', 'good', 'good', 'good', 'good', 'good', 'bad', 'good',
       'good', 'bad', 'good', 'good', 'good', 'good', 'good', 'bad',
       'good', 'bad', 'good', 'good', 'good', 'good', 'bad', 'good',
       'good', 'bad', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'bad', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'bad', 'good', 'good',
       'bad', 'good', 'good', 'good', 'good', 'good', 'good', 'bad',
       'bad', 'good', 'good', 'good', 'bad', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'bad', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'bad', 'good', 'good', 'good', 'bad', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'bad', 'good', 'bad', 'good', 'good', 'good',
       'good', 'bad', 'g

In [93]:
#Visualizando a taxa de acerto0 do modelo
taxa_de_acerto = accuracy_score(y_teste, previsoes)
taxa_de_acerto

0.7233333333333334

In [103]:
#Atribuindo o algoritmo e treinando para criação do modelo
floresta= ExtraTreeClassifier()
floresta.fit(x_treino, y_treino)

ExtraTreeClassifier()

In [48]:
#Observando os atributos mais importantes para seleção de atributo
importantes = floresta.feature_importances_
importantes

array([0.08436597, 0.18156524, 0.24699412, 0.0915581 , 0.09133461,
       0.2223245 , 0.0517754 , 0.03008205])

In [34]:
#Fazendo seleção de atributo em dados de treino e teste
x_treino2= x_treino.iloc[:,[0,1,2,3,5]]
x_teste2 = x_teste.iloc[:,[0,1,2,3,5]]
x_treino2

histórico de crédito  duração  quantidade de crédito   
105                     1       24                  11938  \
68                      3       36                   1819   
479                     1       15                   1478   
399                     1       24                   1516   
434                     3        9                   2136   
..                    ...      ...                    ...   
835                     4       12                   1082   
192                     3       27                   3915   
629                     3        9                   3832   
559                     1       18                   1928   
684                     2       36                   9857   

     compromisso de parcelamento  idade  
105                            2     39  
68                             4     37  
479                            4     44  
399                            4     43  
434                            3     25  
..                           ...    ...  
835                            4     48  
192                            4     36  
629                            1     64  
559                            2     31  
684                            1     31  

[700 rows x 5 columns]

In [69]:
#Atribuindo meu algoritmo e treinando para ver a importância dos meu atributos
floresta2 = ExtraTreeClassifier()
floresta2.fit(x_treino2,y_treino)

ExtraTreeClassifier()

In [70]:
#Vendo a importância dos meu atributos selecionados
Timportante= floresta2.feature_importances_
Timportante

array([0.10112837, 0.1793186 , 0.34467904, 0.0670412 , 0.30783279])

In [94]:
#Atribuindo algoritmo de random forest e treinando para visualizar a performance com atributos selecionado
florestaaleatoria= RandomForestClassifier(n_estimators=300)
florestaaleatoria.fit(x_treino2,y_treino)

RandomForestClassifier(n_estimators=300)

In [95]:
#Fazendo previsão com meu modelo de random forest
previsoes2 = florestaaleatoria.predict(x_teste2)
previsoes

array(['bad', 'good', 'good', 'good', 'good', 'good', 'bad', 'good',
       'good', 'bad', 'good', 'good', 'good', 'good', 'good', 'bad',
       'good', 'bad', 'good', 'good', 'good', 'good', 'bad', 'good',
       'good', 'bad', 'good', 'good', 'good', 'bad', 'good', 'good',
       'good', 'good', 'good', 'bad', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'bad', 'good', 'good', 'good', 'good',
       'bad', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'bad', 'good', 'good', 'good', 'bad', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'bad', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'bad', 'good', 'good', 'good', 'bad', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'bad', 'good', 'good', 'good', 'good', 'good',
       'good', 'bad', '

In [96]:
#Visualizando a taxa de acerto com meu modelo de random forest
taxa_de_acerto2 = accuracy_score(y_teste, previsoes2)
taxa_de_acerto2

0.72

In [105]:
#IMportando algoritmo de árvore de decisão para testa meu atributos com outros modelo
from sklearn.tree import DecisionTreeClassifier

In [106]:
#Atribuindo o algoritmo e treinando para avaliação de meu atributos com outros modelo de algoritmo de classificação
arvore = DecisionTreeClassifier()
arvore.fit(x_treino2,y_treino)

DecisionTreeClassifier()

In [107]:
#Fazendo previsão com meu modelo de árvore de decisão
previsoes3 = arvore.predict(x_teste2)
previsoes3

array(['good', 'good', 'bad', 'good', 'bad', 'bad', 'good', 'good',
       'good', 'good', 'bad', 'good', 'bad', 'good', 'bad', 'bad', 'bad',
       'bad', 'bad', 'bad', 'good', 'good', 'bad', 'good', 'good', 'bad',
       'good', 'bad', 'bad', 'good', 'good', 'good', 'bad', 'bad', 'bad',
       'bad', 'bad', 'good', 'good', 'bad', 'bad', 'good', 'good', 'good',
       'good', 'good', 'good', 'bad', 'good', 'good', 'good', 'bad',
       'good', 'good', 'bad', 'good', 'bad', 'good', 'good', 'good',
       'bad', 'good', 'good', 'bad', 'good', 'good', 'good', 'good',
       'bad', 'good', 'good', 'good', 'bad', 'good', 'bad', 'good', 'bad',
       'bad', 'bad', 'good', 'good', 'bad', 'bad', 'good', 'good', 'good',
       'bad', 'good', 'good', 'good', 'bad', 'good', 'good', 'bad',
       'good', 'good', 'bad', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'bad', 'good', 'good', 'bad', 'bad', 'good', 'bad',
       'good', 'good', 'good', 'good', 'good', 'good', 'bad', 'go

In [108]:
#Visualizando a taxa de acerto com meu modelo de árvore de decisão
taxa_de_acerto3 = accuracy_score(y_teste,previsoes3) 
taxa_de_acerto3

0.6533333333333333

In [109]:
#Importando algoritmo de maquina de vetor de suporte
from sklearn.svm import SVC

In [110]:
#Atribuindo algoritmo de maquina de vetor de suporte e treinando para teste de outros modelo
svm = SVC()
svm.fit(x_treino2,y_treino)

SVC()

In [111]:
#Fazendo previsões com algoritmo de maquina de vetor de suporte
previsoes4 = svm.predict(x_teste2)
previsoes4

array(['good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'bad', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'bad', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'bad', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'g

In [112]:
#Visualizando a taxa de acerto do algoritmo de maquina de vetor de suporte
taxa_de_acerto4 = accuracy_score(y_teste, previsoes4)
taxa_de_acerto4

0.7166666666666667

In [113]:
#Importando algoritmo de neive bayes
from sklearn.naive_bayes import GaussianNB

In [114]:
#Atribuindo e treinando algoritmo de neive bayes
bayes= GaussianNB()
bayes.fit(x_treino2, y_treino)

GaussianNB()

In [115]:
#Fazendo previsões com modelo de algoritmo de neive bayes
previsoes5=bayes.predict(x_teste2)
previsoes5

array(['good', 'good', 'good', 'good', 'bad', 'good', 'good', 'good',
       'good', 'bad', 'bad', 'good', 'good', 'good', 'good', 'good',
       'good', 'bad', 'good', 'good', 'good', 'good', 'bad', 'good',
       'good', 'bad', 'good', 'good', 'good', 'bad', 'good', 'good',
       'good', 'good', 'good', 'bad', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'bad', 'good', 'good', 'good', 'good',
       'bad', 'good', 'good', 'good', 'bad', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'bad', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'bad', 'good', 'good', 'good', 'good', 'good', 'good', 'bad',
       'good', 'good', 'good', 'bad', 'good', 'good', 'good', 'good',
       'good', 'good'

In [117]:
#Visualizando taxa de acerto com algoritmo de neive bayes
taxa_de_acerto5 = accuracy_score(y_teste,previsoes5)
taxa_de_acerto5

0.7266666666666667

In [118]:
#Importando algoritmo de aprendizado baseado em instância
from sklearn.neighbors import KNeighborsClassifier

In [119]:
#Atribuindo e treinando /  criando modelo com algoritmo de aprendizado baseado em instância
abi =  KNeighborsClassifier()
abi.fit(x_treino2, y_treino)

KNeighborsClassifier()

In [120]:
#Fazendo previsões com meu modelo de algoritmo de aprendizado baseado em instância
previsoes6=abi.predict(x_teste2)
previsoes6

array(['good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'bad', 'good', 'good', 'good', 'bad', 'good', 'good', 'bad',
       'good', 'good', 'good', 'bad', 'good', 'bad', 'good', 'good',
       'good', 'good', 'good', 'bad', 'good', 'good', 'good', 'bad',
       'bad', 'bad', 'good', 'bad', 'good', 'good', 'good', 'good', 'bad',
       'good', 'good', 'good', 'good', 'good', 'bad', 'bad', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'bad',
       'good', 'good', 'good', 'bad', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'bad', 'good', 'bad', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'bad', 'good', 'good', 'good', 'bad', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'bad', 'good',
       'good', 'good', 'good', 'bad', 'good', 'good', 'good', 'bad',
       'bad', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good'

In [121]:
#Visualizando a taxa de acerto com algoritmo de aprendizado baseado em instância
taxa_de_acerto6 = accuracy_score(y_teste, previsoes6)
taxa_de_acerto5

0.7266666666666667

In [12]:
#Importando algoritmo de rede neural e TensorFlow
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
import tensorflow as tf

In [61]:
#Separando meus dados de previsores e classe
previsores2 = credito.iloc[:,0:8]
classe2 = credito.iloc[:, 8]
classe2

0      good
1       bad
2      good
3      good
4       bad
       ... 
995    good
996    good
997    good
998     bad
999    good
Name: class, Length: 1000, dtype: object

In [8]:
#Transformando dados categorizo de previsores em numérico
encoding2 = LabelEncoder()
previsores2.iloc[:,0] = encoding2.fit_transform(previsores2.iloc[:, 0]
                       )
previsores2

histórico de crédito  duração  quantidade de crédito   
0                      1        6                   1169  \
1                      3       48                   5951   
2                      1       12                   2096   
3                      3       42                   7882   
4                      2       24                   4870   
..                   ...      ...                    ...   
995                    3       12                   1736   
996                    3       30                   3857   
997                    3       12                    804   
998                    3       45                   1845   
999                    1       45                   4576   

     compromisso de parcelamento  residência desde  idade   
0                              4                 4     67  \
1                              2                 2     22   
2                              2                 3     49   
3                              2                 4     45   
4                              3                 4     53   
..                           ...               ...    ...   
995                            3                 4     31   
996                            4                 4     40   
997                            4                 4     38   
998                            4                 4     23   
999                            3                 4     27   

     créditos existentes  número de dependentes  
0                      2                      1  
1                      1                      1  
2                      1                      2  
3                      1                      2  
4                      2                      2  
..                   ...                    ...  
995                    1                      1  
996                    1                      1  
997                    1                      1  
998                    1                      1  
999                    1                      1  

[1000 rows x 8 columns]

In [9]:
#transformando minha classe de dados categóricos em numérico 
encoding_class=LabelEncoder()
classe2=encoding_class.fit_transform(classe2)
classe2

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,

In [35]:
#Separando dados de treino e teste com 30% de teste e o resto de treino
x_treino3, x_teste3 ,y_treino3, y_teste3 = train_test_split(previsores2, classe2 , test_size=0.3, random_state=0 )
y_teste3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0])

In [13]:
#Transformando dados inteiro para float para transforma em tensor
x_treino3=x_treino3.astype("float32")
x_teste3 =  x_teste3.astype("float32")



histórico de crédito  duração  quantidade de crédito   
105                   1.0     24.0                11938.0  \
68                    3.0     36.0                 1819.0   
479                   1.0     15.0                 1478.0   
399                   1.0     24.0                 1516.0   
434                   3.0      9.0                 2136.0   
..                    ...      ...                    ...   
835                   4.0     12.0                 1082.0   
192                   3.0     27.0                 3915.0   
629                   3.0      9.0                 3832.0   
559                   1.0     18.0                 1928.0   
684                   2.0     36.0                 9857.0   

     compromisso de parcelamento  residência desde  idade   
105                          2.0               3.0   39.0  \
68                           4.0               4.0   37.0   
479                          4.0               4.0   44.0   
399                          4.0               1.0   43.0   
434                          3.0               2.0   25.0   
..                           ...               ...    ...   
835                          4.0               4.0   48.0   
192                          4.0               2.0   36.0   
629                          1.0               4.0   64.0   
559                          2.0               2.0   31.0   
684                          1.0               3.0   31.0   

     créditos existentes  número de dependentes  
105                  2.0                    2.0  
68                   1.0                    1.0  
479                  2.0                    2.0  
399                  2.0                    1.0  
434                  1.0                    1.0  
..                   ...                    ...  
835                  2.0                    1.0  
192                  1.0                    2.0  
629                  1.0                    1.0  
559                  2.0                    1.0  
684                  2.0                    2.0  

[700 rows x 8 columns]

In [14]:
#Transformando dados de trino e teste em tensor para a leitura da rede neural
x_teste4=tf.constant(x_teste3)
x_treino4 = tf.constant(x_treino3)
x_treino4

<tf.Tensor: shape=(700, 8), dtype=float32, numpy=
array([[1.0000e+00, 2.4000e+01, 1.1938e+04, ..., 3.9000e+01, 2.0000e+00,
        2.0000e+00],
       [3.0000e+00, 3.6000e+01, 1.8190e+03, ..., 3.7000e+01, 1.0000e+00,
        1.0000e+00],
       [1.0000e+00, 1.5000e+01, 1.4780e+03, ..., 4.4000e+01, 2.0000e+00,
        2.0000e+00],
       ...,
       [3.0000e+00, 9.0000e+00, 3.8320e+03, ..., 6.4000e+01, 1.0000e+00,
        1.0000e+00],
       [1.0000e+00, 1.8000e+01, 1.9280e+03, ..., 3.1000e+01, 2.0000e+00,
        1.0000e+00],
       [2.0000e+00, 3.6000e+01, 9.8570e+03, ..., 3.1000e+01, 2.0000e+00,
        2.0000e+00]], dtype=float32)>

In [16]:
#Atribuindo algoritmo de rede neural
modelo = Sequential()
#ADICIONANDO CAMADAS DENSA COM 6 NEURÔNIOS, INICIALIZAÇÃO DA KERNEL UNIFORME, ATIVAÇÃO COM RELU E CAMADA DE ENTRADA DE DADOS COM 8 
modelo.add(Dense(units=6, kernel_initializer="uniform", activation="relu", input_dim=8))
#ADICIONANDO CAMADAS DENSA COM 6 NEURÔNIOS, INICIALIZAÇÃO DA KERNEL UNIFORME, ATIVAÇÃO COM RELU 
modelo.add(Dense(units=6 , kernel_initializer="uniform", activation="relu"))
#ADICIONANDO CAMADAS DENSA COM 6 NEURÔNIOS, INICIALIZAÇÃO DA KERNEL UNIFORME, ATIVAÇÃO COM DE SAIDA SIGMOID PARA CLASSE SAIR EM MODO BINÁRIO
modelo.add(Dense(units=1 , kernel_initializer= "uniform", activation="sigmoid"))
#Compilando com otimização com SGD PARA ENCONTRA O MELHOR MODELO, LOSS COM BC, METRICAS COM ACCURACY
modelo.compile(optimizer=SGD(lr=0.01), loss="binary_crossentropy", metrics=["accuracy"])
#TREINANDO COM 1000 EPOCHS E VALIDAÇÃO COM DADOS DE TESTE
modelo.fit(x_treino4,y_treino3, epochs=1000, validation_data= (x_teste4,y_teste3))


Epoch 1/1000


c:\Users\Valdir Oliveira\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\optimizers\legacy\gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


22/22 [==============================] - 2s 15ms/step - loss: 0.6898 - accuracy: 0.6600 - val_loss: 0.6845 - val_accuracy: 0.7133
Epoch 2/1000
22/22 [==============================] - 0s 4ms/step - loss: 0.6819 - accuracy: 0.6943 - val_loss: 0.6767 - val_accuracy: 0.7133
Epoch 3/1000
22/22 [==============================] - 0s 4ms/step - loss: 0.6752 - accuracy: 0.6943 - val_loss: 0.6696 - val_accuracy: 0.7133
Epoch 4/1000
22/22 [==============================] - 0s 4ms/step - loss: 0.6692 - accuracy: 0.6943 - val_loss: 0.6633 - val_accuracy: 0.7133
Epoch 5/1000
22/22 [==============================] - 0s 4ms/step - loss: 0.6638 - accuracy: 0.6943 - val_loss: 0.6576 - val_accuracy: 0.7133
Epoch 6/1000
22/22 [==============================] - 0s 4ms/step - loss: 0.6590 - accuracy: 0.6943 - val_loss: 0.6524 - val_accuracy: 0.7133
Epoch 7/1000
22/22 [==============================] - 0s 5ms/step - loss: 0.6547 - accuracy: 0.6943 - val_loss: 0.6478 - val_accuracy: 0.7133
Epoch 8/1000
22/22

In [22]:
#fazendo previsão com meu modelo de rede neural 
previsoes7=modelo.predict(x_teste4)

10/10 [==============================] - 0s 2ms/step


array([0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553,
       0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553,
       0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553,
       0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553,
       0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553,
       0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553,
       0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553,
       0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553,
       0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553,
       0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553,
       0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553,
       0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553,
       0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553, 0.6944553,
       0.6944553, 0.6944553, 0.6944553, 0.6944553, 

In [24]:
#Atribuindo valores da previsão em forma de boleando
teste7=previsoes7 > 0.5

In [33]:
#Visualizando taxa de acerto com modelo de rede neural
taxa_de_acerto7 =  accuracy_score(y_teste3,teste7)
taxa_de_acerto7

0.7133333333333334

In [27]:
#IMPORTANDO NUMPY
import numpy as np

In [50]:
#Visualizando número de verdadeiro ou falso
print(len(teste7[teste7 == False]))
print(len(teste7[teste7 == True]))

0
300


In [57]:
#IMPORTANDO MATRIX DE CONFUSÃO
from sklearn.metrics import confusion_matrix

In [60]:
#VISUALIZANDO ACERTOS E ERROS DO MODELO DE REDE NEURAL
matriz = confusion_matrix(y_teste3,teste7 )
matriz

array([[  0,  86],
       [  0, 214]], dtype=int64)

In [69]:
#FAZENDO SELEÇÃO DE ATRIBUTO PARA UM NOVO TESTE DE REDE NEURAL
x_teste5= x_teste3.iloc[:,[0,1,2,3,5]]
x_treino5 = x_treino3.iloc[:,[0,1,2,3,5]]
x_treino5

histórico de crédito  duração  quantidade de crédito   
105                    1       24                  11938  \
68                     3       36                   1819   
479                    1       15                   1478   
399                    1       24                   1516   
434                    3        9                   2136   
..                   ...      ...                    ...   
835                    4       12                   1082   
192                    3       27                   3915   
629                    3        9                   3832   
559                    1       18                   1928   
684                    2       36                   9857   

     compromisso de parcelamento  idade  
105                            2     39  
68                             4     37  
479                            4     44  
399                            4     43  
434                            3     25  
..                           ...    ...  
835                            4     48  
192                            4     36  
629                            1     64  
559                            2     31  
684                            1     31  

[700 rows x 5 columns]

In [70]:
#Transformando dados inteiro para float para transforma em tensor
x_treino5 = x_treino5.astype('float32')
x_teste5 = x_teste5.astype("float32")
x_treino5

histórico de crédito  duração  quantidade de crédito   
105                   1.0     24.0                11938.0  \
68                    3.0     36.0                 1819.0   
479                   1.0     15.0                 1478.0   
399                   1.0     24.0                 1516.0   
434                   3.0      9.0                 2136.0   
..                    ...      ...                    ...   
835                   4.0     12.0                 1082.0   
192                   3.0     27.0                 3915.0   
629                   3.0      9.0                 3832.0   
559                   1.0     18.0                 1928.0   
684                   2.0     36.0                 9857.0   

     compromisso de parcelamento  idade  
105                          2.0   39.0  
68                           4.0   37.0  
479                          4.0   44.0  
399                          4.0   43.0  
434                          3.0   25.0  
..                           ...    ...  
835                          4.0   48.0  
192                          4.0   36.0  
629                          1.0   64.0  
559                          2.0   31.0  
684                          1.0   31.0  

[700 rows x 5 columns]

In [71]:
#Transformando dados de trino e teste em tensor para a leitura da rede neural
x_treino5 = tf.constant(x_treino5)
x_teste5 = tf.constant(x_teste5)
x_treino5

<tf.Tensor: shape=(700, 5), dtype=float32, numpy=
array([[1.0000e+00, 2.4000e+01, 1.1938e+04, 2.0000e+00, 3.9000e+01],
       [3.0000e+00, 3.6000e+01, 1.8190e+03, 4.0000e+00, 3.7000e+01],
       [1.0000e+00, 1.5000e+01, 1.4780e+03, 4.0000e+00, 4.4000e+01],
       ...,
       [3.0000e+00, 9.0000e+00, 3.8320e+03, 1.0000e+00, 6.4000e+01],
       [1.0000e+00, 1.8000e+01, 1.9280e+03, 2.0000e+00, 3.1000e+01],
       [2.0000e+00, 3.6000e+01, 9.8570e+03, 1.0000e+00, 3.1000e+01]],
      dtype=float32)>

In [78]:
#Atribuindo algoritmo de rede neural
modelo2 = Sequential()
#ADICIONANDO CAMADAS DENSA COM 5 NEURÔNIOS, INICIALIZAÇÃO DA KERNEL UNIFORME, ATIVAÇÃO COM RELU E CAMADA DE ENTRADA DE DADOS COM 5
modelo2.add(Dense(units=5, kernel_initializer="uniform", activation="relu", input_dim=5))
#ADICIONANDO CAMADAS DENSA COM 5 NEURÔNIOS, INICIALIZAÇÃO DA KERNEL UNIFORME, ATIVAÇÃO COM RELU
modelo2.add(Dense(units=5, kernel_initializer="uniform", activation="relu",))
#ADICIONANDO CAMADAS DENSA DE SAIDA COM 1 NEURÔNIOS, INICIALIZAÇÃO DA KERNEL UNIFORME, ATIVAÇÃO COM SIGMOID PARA SAIDA BINARIA
modelo2.add(Dense(units=1, kernel_initializer="uniform", activation= "sigmoid" ))
#Compilando com otimização com SGD PARA ENCONTRA O MELHOR MODELO, LOSS COM BC, METRICAS COM ACCURACY
modelo2.compile(optimizer=SGD(lr=0.01), loss="binary_crossentropy", metrics=["accuracy"])
#TREINANDO COM 1000 EPOCHS E VALIDAÇÃO COM DADOS DE TESTE
modelo2.fit(x_treino5,y_treino3, epochs=1000, validation_data=(x_teste5,y_teste3) )

c:\Users\Valdir Oliveira\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\optimizers\legacy\gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Epoch 1/1000
22/22 [==============================] - 9s 29ms/step - loss: 0.6894 - accuracy: 0.6743 - val_loss: 0.6845 - val_accuracy: 0.7133
Epoch 2/1000
22/22 [==============================] - 0s 4ms/step - loss: 0.6819 - accuracy: 0.6943 - val_loss: 0.6767 - val_accuracy: 0.7133
Epoch 3/1000
22/22 [==============================] - 0s 4ms/step - loss: 0.6752 - accuracy: 0.6943 - val_loss: 0.6697 - val_accuracy: 0.7133
Epoch 4/1000
22/22 [==============================] - 0s 4ms/step - loss: 0.6692 - accuracy: 0.6943 - val_loss: 0.6633 - val_accuracy: 0.7133
Epoch 5/1000
22/22 [==============================] - 0s 6ms/step - loss: 0.6638 - accuracy: 0.6943 - val_loss: 0.6577 - val_accuracy: 0.7133
Epoch 6/1000
22/22 [==============================] - 0s 4ms/step - loss: 0.6590 - accuracy: 0.6943 - val_loss: 0.6525 - val_accuracy: 0.7133
Epoch 7/1000
22/22 [==============================] - 0s 4ms/step - loss: 0.6547 - accuracy: 0.6943 - val_loss: 0.6478 - val_accuracy: 0.7133
Epoch

In [79]:
#Fazendo previsões com meu modelo de rede neural
previsoes8=modelo2.predict(x_teste5)
previsoes8

10/10 [==============================] - 0s 1ms/step


array([[0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],
       [0.6942401],


In [80]:
#Separando falsos e verdadeiro em true e false 
pred=previsoes8>0.5
pred

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [81]:
#Visualizando a taxa de acerto
taxa_de_acerto8 = accuracy_score(y_teste3, pred)
taxa_de_acerto8

0.7133333333333334

In [82]:
#VISUALIZANDO A QUANTIDADE E ERRO E ACERTOS
matrix = confusion_matrix(y_teste3, pred)
matrix


array([[  0,  86],
       [  0, 214]], dtype=int64)

#MELHORES MODELOS FOI COM ALGORITMO DE NAIVE BEYES É APRENDIZADO BASEADO EM INSTANCIAS, ALGUNS MODELO NÃO CONSEGUIU FICAR GENÉRICO COMO REDE NEURAL
#PARA MELHORA DESSES MODELO DEVERIA TER MAIS DADOS  